![](img/the_real_reason.png)

# Tutorial Overview

This repository: https://github.com/sotte/pytorch_tutorial

Original title:
~~Deep Neural Networks with PyTorch~~

Better title:
PyTorch: Deep Neural Networks and more


Prerequisites:
- you have implemented machine learning models yourself
- you know what deep learning is
- you have used numpy
- maybe you have used tensorflow or similar libs
- if you use PyTorch on a daily basis, this tutorial is probably not for you

Goals:
- understand PyTorch
- overview of all concepts
- be able to use transfer learning in PyTorch
- know some handy tools/libs

Note:
You don't need a GPU to work on this tutorial, but everything is much faster if you have one.
However, you can use Google's Colab with a GPU and work on this tutorial:
[PyTorch + GPU in Google's Colab](0X_pytorch_in_googles_colab.ipynb)

# Agenda

- [00 Index](00_index.ipynb) <- this document
- [01 PyTorch basics: tensors, autograd, debugging](01_pytorch_basics.ipynb)
- [02 PyTorch concepts: dataset, dataloader, sampler, transforms](02_pytorch_concepts.ipynb)
- [03 Transfer Learning + Visualization + Tools](03_transfer_learning.ipynb)
- Intermissions:
  - [PyTorch + GPU in Google's Colab](0X_pytorch_in_googles_colab.ipynb)
  - [Teacher Forcing](0X_teacher_forcing.ipynb)
  - [RNNs from Scratch](0X_rnn_from_scratch.ipynb)
  - [Mean Shift Clustering](0X_mean_shift_clustering.ipynb)
  - [Machine Learning 101 with numpy and PyTorch](0X_machine_learning_101.ipynb)
- [09 The_End](09_the_end.ipynb)

# PyTorch Overview


> "PyTorch - Tensors and Dynamic neural networks in Python
with strong GPU acceleration.
PyTorch is a deep learning framework for fast, flexible experimentation."
-- https://pytorch.org/*

![](img/dynamic_graph.gif)

This is a much better explanation of PyTorch (I think)

In [1]:
import torch
from IPython.core.debugger import set_trace

def f(x):
    res = x + x
    set_trace()  # <-- OMG! =D
    return res

x = torch.randn(1, 10)
f(x)

> <ipython-input-1-e135fc686baa>(7)f()
      5     res = x + x
      6     set_trace()  # <-- OMG! =D
----> 7     return res
      8 
      9 x = torch.randn(1, 10)

ipdb> res
tensor([[ 2.6046, -0.2339,  2.5349,  3.0637, -4.0668, -1.3110,  0.0847,  1.4221,
         -3.3597, -2.9848]])
ipdb> x
tensor([[ 1.3023, -0.1169,  1.2674,  1.5318, -2.0334, -0.6555,  0.0423,  0.7111,
         -1.6798, -1.4924]])
ipdb> x+x
tensor([[ 2.6046, -0.2339,  2.5349,  3.0637, -4.0668, -1.3110,  0.0847,  1.4221,
         -3.3597, -2.9848]])
ipdb> x-2
tensor([[-0.6977, -2.1169, -0.7326, -0.4682, -4.0334, -2.6555, -1.9577, -1.2889,
         -3.6798, -3.4924]])
ipdb> x^2
*** RuntimeError: bitxor is only supported for integer type tensors at /Users/administrator/nightlies/pytorch-1.0.0/wheel_build_dirs/conda_2.7/conda/conda-bld/pytorch_1544135070245/work/aten/src/TH/generic/THTensorMath.cpp:75
ipdb> x**@
*** SyntaxError: invalid syntax (<stdin>, line 1)
ipdb> exit


BdbQuit: 

I like pytorch because
- "it's just stupid python"
- easy to debug
- nice and extensible interface
- research-y feel
- research is often published as pytorch project

## *"The tyranny of choice"* - other libraries
- torch
- TensorFlow
- MXNet
- Keras
- CNTK
- caffe
- caffe2
- many many more


## References
- Twitter: https://twitter.com/PyTorch
- Tutorials: https://pytorch.org/tutorials/
- Examples: https://github.com/pytorch/examples
- API Reference: https://pytorch.org/docs/stable/index.html
- Torchvision: https://pytorch.org/docs/stable/torchvision/index.html
- PyTorch Text: https://github.com/pytorch/text
- PyTorch Audio: https://github.com/pytorch/audio
- Facebook AI Research Sequence-to-Sequence Toolkit written in PyTorch: https://github.com/pytorch/fairseq
- FastAI http://www.fast.ai/
- Stanford CS230 Deep Learning notes https://cs230-stanford.github.io

# Example Network
Just to get an idea of how pytorch feels like here are some examples of networks.

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [9]:
# great idea write out the named parameters to learn coding faster

In [3]:
from collections import OrderedDict

# Simple sequential model
layers = OrderedDict([
    ('conv1', nn.Conv2d(in_channels=1, out_channels=20, kernel_size=5)),
    ('relu1', nn.ReLU()),
    ('conv2', nn.Conv2d(20,64,5)),
    ('relu2', nn.ReLU())
])
model = nn.Sequential(layers)

In [10]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(in_channels=3, out_channels=6, kernel_size=5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(in_channels=6, out_channels=16, kernel_size=5)
        self.fc1 = nn.Linear(in_features=16 * 5 * 5, out_features=120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)
    
    # define the conv layers above pooling and fully connected layers
    # first run convolution, pass through relu activation, then 
    # pass through pooling
    # reshape using view
    # fully connected, then through relu activation

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1, 16 * 5 * 5)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x


net = Net()

# Versions

In [11]:
import torch
torch.__version__

'1.0.0'

In [6]:
import torchvision
torchvision.__version__

'0.2.1'

In [7]:
import numpy as np
np.__version__

'1.14.2'

In [8]:
import ignite
ignite.__version__

ImportError: No module named ignite